Algoritmo "Atividade 01"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Gabriel Magalhães Silva
// Data atual  : 29/02/2024
Var
  num,cont,soma:inteiro


Inicio
soma <-0
cont <- 1
  enquanto (cont <= 10) faca
  escreval("Digite o ", cont, "º número: ")
  leia(num)
  soma <- soma + num
  cont <- cont + 1
 fimEnquanto
escreval("A soma dos 10 números é:", soma)

Fimalgoritmo